config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
   get 'home/about' => 'homes#about' , as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]  do
       resource :favorites, only: [:create, :destroy]
     resources :book_comments, only: [:create, :destroy]
  end
   resources :users, only: [:index, :show, :edit, :update]
   
   
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  validates :name, uniqueness: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
   
  def after_sign_out_path_for(resource)
    root_path
    
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to request.referer
  end
  
  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to request.referer
  end
  
  
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
 

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was successfully created"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice] = "Book was successfully updated."
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save 
    redirect_to request.referer
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def index
    @user = current_user
    @users = User.all
    @book =Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
     @user = User.find(params[:id])
     if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:notice] = "User was successfully updated."
     else
      render:edit
     end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(user_path(current_user)) unless @user == current_user
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container mt-3">
  <% if @book.errors.any? %>
      <%= @book.errors.count %> error prohibited this book from being saved:
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	
  		<%= form_with model: @book do |f| %>
  		 
        <div class="field mb-3">
          <label :book_title>Title</label><br>
          <%= f.text_field :title ,autofocus: true,class:"form-control btn-block" %>
        </div>
      
        <div class="field mb-3">
          <label :book_opinion>Opinion</label><br>
          <%= f.text_area :body  ,class:"form-control btn-block" %>
        </div>
        
        <div class="mb-3 ">
          <%= f.submit "Update Book" ,class:"btn bg-success text-light" %>
        </div>
     <% end %>
     
     <%= link_to "Show", book_path(@book) %>
     |
     <%= link_to "Back", books_path %>
   </div>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
   <% if @book.errors.any? %>
      <%= @book.errors.count %> error prohibited this book from being saved:
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    <% end %>
　<div class='row'>
    <%= render'users/userinfo', user: @user , book: @book %>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag @user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td>
                <% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book), method: :delete do %>
                   <i class="fa-solid fa-heart"></i><%= book.favorites.count %>いいね
                <% end %>
                <% else %>
                <%= link_to book_favorites_path(book), method: :post do %>
                   <i class="fa-solid fa-heart"></i><%= book.favorites.count %>いいね
                <% end %>
              <% end %>
              </td>
              <td>
                <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<div class='container px-5 px-sm-0'>
　<div class='row'>
    <%= render'users/userinfo', user: @user , book: @book_new %>
    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <td>
                <%= image_tag @user.get_profile_image(100,100) %><br>
                <%= link_to user_path(@user) do %>
                  <%= @user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book) do %>
                  <%= @book.title %>
                <% end %>
              </td>
              <td>
                <%= @book.body %>
              </td>
          <% if @book.user == current_user %>
             <td>
                 <%= link_to "Edit", edit_book_path(@book) ,class:"btn btn-sm text-light bg-success" %>
             </td>
                 
              <td>
                 <%= link_to "Destroy",book_path(@book), method: :delete ,class:"btn btn-sm bg-danger text-light" %>
              </td>
          <% end %>
            </td>
            <td>
              <% if @book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(@book), method: :delete do %>
                   <i class="fa-solid fa-heart"></i><%= @book.favorites.count %>いいね
                <% end %>
                <% else %>
                <%= link_to book_favorites_path(@book), method: :post do %>
                  <i class="fa-solid fa-heart"></i><%= @book.favorites.count %>いいね
                <% end %>
              <% end %>
            </td>
            <td>
              コメント数: <%= @book.book_comments.count %>
            </td>
          <tr>
            <td>
              <% @book.book_comments.each do |book_comment| %>
                <%= image_tag book_comment.user.get_profile_image(100,100) %>
                <%= book_comment.comment %>
                <% if book_comment.user == current_user %>
                  <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete ,class:" btn btn-sm bg-danger text-light " %>
                <% end %><br>
                <%= link_to books_path do %>
                  <%= book_comment.user.name %><br>
                <% end %>
              <% end %>
            </td>
          </tr>
          </tr>
        </tbody>
      </table>
      
     <div>
       <%= form_with model: [@book, @book_comment] do |f| %>
         <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" ,class:" btn-block"%>
         <%= f.submit "送信" , class:"mt-1" %>
      <% end %>
     </div>
      
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="p-3 mx-auto">
      <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>

    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="p-3 mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in"%>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/0b9b03c08a.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="mx-auto"> 
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Bookers</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">

      <% if user_signed_in? %>
        <li>
          <%= link_to user_path(current_user), class: "nav-link text-light" do %>
          <i class= "fas fa-home"></i>Home
      <% end %>
        </li>

      <li>
        <%= link_to users_path, class: "nav-link text-light" do %>
        <i class= "fas fa-users"></i>Users
        <% end %>
      </li>

      <li>
        <%= link_to books_path, class: "nav-link text-light" do %>
        <i class= "fas fa-book-open"></i>Books
        <% end %>
      </li>

      <li>
        <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
        <i class= "fas fa-sign-out-alt"></i>Log out
        <% end %>
      </li>

    <% else %>

      <li>
        <%= link_to root_path, class: "nav-link text-light" do %>
          <i class="fas fa-home"></i>Home
        <% end %>
      </li>

      <li>
        <%= link_to about_path, class: "nav-link text-light" do %>
        <i class= "fas fa-link"></i>About
        <% end %>
      </li>

      <li>
        <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
        <i class="fas fa-user-plus"></i>Sign up
        <% end %>
      </li>
      <li>
        <%= link_to new_user_session_path, class: "nav-link text-light" do %>
        <i class="fas fa-sign-in-alt"></i>Log in
        <% end %>
      </li>
    <% end %>
    </ul>

     </div>
   </nav>
   　<%= flash[:notice] %>
    <%= yield %>
  </body>
</html>



  

app/views/users/_userinfo.html.erb
<div class='col-md-3'>
  <h2>User info</h2>
  <table class='table'>
    <tbody>
      <tr><%= image_tag user.get_profile_image(100,100) %></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  
    <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>

  <h1>New book</h1>
  <%= form_with model: book do |f| %>

    <h4>title</h4>
    <%= f.text_field :title ,class:" btn-block" %>

    <h4>opinion</h4>
    <%= f.text_area :body ,class:" btn-block"%>
    
    <%= f.submit 'Create Book', class: "btn btn-success btn-block"%>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container mt-3">
  <% if @user.errors.any? %>
    <%= @user.errors.count %>errors prohibited this book from being saved:
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  	  <h1>User info</h1>
    	
  		<%= form_with model: @user do |f| %>
  		 
        <div class="field mb-3">
          <label for="user_name">Name</label><br>
           <%= f.text_field :name, autofocus: true,  placeholder:"名前"  ,class:"form-control btn-block"%>
        </div>
      
        <div class="field mb-3">
          <label for ="user_name">Image</label><br>
          <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
        </div>
        <div class="mb-3 ">
         <label for="user_name">Introduction</label><br>
         <%= f.text_area :introduction, placeholder: "自己紹介"  %>
        </div>
        <div class="mb-3 ">
          <%= f.submit "Update User" ,class:"btn bg-secondary text-light"%>
        </div>
     <% end %>
     
   </div>
  </div>
</div>











  
  
  
  

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <%= render'userinfo', user: @user , book: @book %>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= image_tag user.get_profile_image(100,100) %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to "Show", user_path(user.id) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <%= render'userinfo', user: @user , book: @book %>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td>
                <% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book), method: :delete do %>
                   <i class="fa-solid fa-heart"></i><%= book.favorites.count %>いいね
                <% end %>
                <% else %>
                <%= link_to book_favorites_path(book), method: :post do %>
                   <i class="fa-solid fa-heart"></i><%= book.favorites.count %>いいね
                <% end %>
                <% end %>
              </td>
              <td>
                <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>